# Generated by Django 4.1.12 on 2024-04-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admodel',
            name='Description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
