# Generated by Django 4.1.12 on 2024-04-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_alter_admodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=30)),
                ('img', models.ImageField(blank=True, default='image/1713541114603.jpg', null=True, upload_to='image/')),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
