# Generated by Django 4.1.12 on 2024-04-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img',
        ),
        migrations.AddField(
            model_name='image',
            name='dir',
            field=models.ImageField(blank=True, default='image/1713541179286.jpg', null=True, upload_to='image/'),
        ),
    ]
