# Generated by Django 4.1.12 on 2024-04-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_remove_image_img_image_dir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='dir',
        ),
        migrations.AddField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, default='image/1713541223231.jpg', null=True, upload_to='image/'),
        ),
    ]
