# Generated by Django 4.1.12 on 2024-04-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_alter_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, default='image/1713598901381.jpg', null=True, upload_to='image/'),
        ),
    ]
